name: Test and Deploy
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v5
            - name: Install Node
              uses: actions/setup-node@v5
              with:
                node-version: 18
            - name: Linting the code
              run: npm lint
            - name: Install dependencies
              run: npm install
            - name: Build the project
              run: npm build 
            - name: Deploy the project
              run: echo "Deploying!!!!!!!!"